name: "Tagged Release"

on:
  push:
    tags:
      - "**"

jobs:
  tagged-release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.HUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release for WOTLKC
        uses: BigWigsMods/packager@v2
        with:
          args: -m .pkgmeta -g -S -w 0 -a 0
